window.UPCORRETOR_THEMES = [
  {
    "id": "tema-01",
    "name": "Folha 1",
    "palette": "Folha",
    "primary": "#1d6b4c",
    "background": "#f5f7f4",
    "text": "#17201b",
    "surface": "#dcefe5",
    "font": "Inter",
    "spacing": "compact",
    "radius": 8,
    "layout": "Horizonte"
  },
  {
    "id": "tema-02",
    "name": "Folha 2",
    "palette": "Folha",
    "primary": "#1d6b4c",
    "background": "#f5f7f4",
    "text": "#17201b",
    "surface": "#dcefe5",
    "font": "Sora",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Editorial"
  },
  {
    "id": "tema-03",
    "name": "Folha 3",
    "palette": "Folha",
    "primary": "#1d6b4c",
    "background": "#f5f7f4",
    "text": "#17201b",
    "surface": "#dcefe5",
    "font": "Poppins",
    "spacing": "airy",
    "radius": 22,
    "layout": "Galeria"
  },
  {
    "id": "tema-04",
    "name": "Folha 4",
    "palette": "Folha",
    "primary": "#1d6b4c",
    "background": "#f5f7f4",
    "text": "#17201b",
    "surface": "#dcefe5",
    "font": "DM Sans",
    "spacing": "compact",
    "radius": 8,
    "layout": "Essencial"
  },
  {
    "id": "tema-05",
    "name": "Folha 5",
    "palette": "Folha",
    "primary": "#1d6b4c",
    "background": "#f5f7f4",
    "text": "#17201b",
    "surface": "#dcefe5",
    "font": "Montserrat",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Ateliê"
  },
  {
    "id": "tema-06",
    "name": "Oceano 1",
    "palette": "Oceano",
    "primary": "#166b8f",
    "background": "#f3f8fa",
    "text": "#102a35",
    "surface": "#d7edf4",
    "font": "Inter",
    "spacing": "airy",
    "radius": 22,
    "layout": "Horizonte"
  },
  {
    "id": "tema-07",
    "name": "Oceano 2",
    "palette": "Oceano",
    "primary": "#166b8f",
    "background": "#f3f8fa",
    "text": "#102a35",
    "surface": "#d7edf4",
    "font": "Sora",
    "spacing": "compact",
    "radius": 8,
    "layout": "Editorial"
  },
  {
    "id": "tema-08",
    "name": "Oceano 3",
    "palette": "Oceano",
    "primary": "#166b8f",
    "background": "#f3f8fa",
    "text": "#102a35",
    "surface": "#d7edf4",
    "font": "Poppins",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Galeria"
  },
  {
    "id": "tema-09",
    "name": "Oceano 4",
    "palette": "Oceano",
    "primary": "#166b8f",
    "background": "#f3f8fa",
    "text": "#102a35",
    "surface": "#d7edf4",
    "font": "DM Sans",
    "spacing": "airy",
    "radius": 22,
    "layout": "Essencial"
  },
  {
    "id": "tema-10",
    "name": "Oceano 5",
    "palette": "Oceano",
    "primary": "#166b8f",
    "background": "#f3f8fa",
    "text": "#102a35",
    "surface": "#d7edf4",
    "font": "Montserrat",
    "spacing": "compact",
    "radius": 8,
    "layout": "Ateliê"
  },
  {
    "id": "tema-11",
    "name": "Terracota 1",
    "palette": "Terracota",
    "primary": "#b4553d",
    "background": "#fbf5f1",
    "text": "#38201b",
    "surface": "#f5dfd6",
    "font": "Inter",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Horizonte"
  },
  {
    "id": "tema-12",
    "name": "Terracota 2",
    "palette": "Terracota",
    "primary": "#b4553d",
    "background": "#fbf5f1",
    "text": "#38201b",
    "surface": "#f5dfd6",
    "font": "Sora",
    "spacing": "airy",
    "radius": 22,
    "layout": "Editorial"
  },
  {
    "id": "tema-13",
    "name": "Terracota 3",
    "palette": "Terracota",
    "primary": "#b4553d",
    "background": "#fbf5f1",
    "text": "#38201b",
    "surface": "#f5dfd6",
    "font": "Poppins",
    "spacing": "compact",
    "radius": 8,
    "layout": "Galeria"
  },
  {
    "id": "tema-14",
    "name": "Terracota 4",
    "palette": "Terracota",
    "primary": "#b4553d",
    "background": "#fbf5f1",
    "text": "#38201b",
    "surface": "#f5dfd6",
    "font": "DM Sans",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Essencial"
  },
  {
    "id": "tema-15",
    "name": "Terracota 5",
    "palette": "Terracota",
    "primary": "#b4553d",
    "background": "#fbf5f1",
    "text": "#38201b",
    "surface": "#f5dfd6",
    "font": "Montserrat",
    "spacing": "airy",
    "radius": 22,
    "layout": "Ateliê"
  },
  {
    "id": "tema-16",
    "name": "Areia 1",
    "palette": "Areia",
    "primary": "#9a6b38",
    "background": "#fbf8f1",
    "text": "#33281d",
    "surface": "#f1e6d2",
    "font": "Inter",
    "spacing": "compact",
    "radius": 8,
    "layout": "Horizonte"
  },
  {
    "id": "tema-17",
    "name": "Areia 2",
    "palette": "Areia",
    "primary": "#9a6b38",
    "background": "#fbf8f1",
    "text": "#33281d",
    "surface": "#f1e6d2",
    "font": "Sora",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Editorial"
  },
  {
    "id": "tema-18",
    "name": "Areia 3",
    "palette": "Areia",
    "primary": "#9a6b38",
    "background": "#fbf8f1",
    "text": "#33281d",
    "surface": "#f1e6d2",
    "font": "Poppins",
    "spacing": "airy",
    "radius": 22,
    "layout": "Galeria"
  },
  {
    "id": "tema-19",
    "name": "Areia 4",
    "palette": "Areia",
    "primary": "#9a6b38",
    "background": "#fbf8f1",
    "text": "#33281d",
    "surface": "#f1e6d2",
    "font": "DM Sans",
    "spacing": "compact",
    "radius": 8,
    "layout": "Essencial"
  },
  {
    "id": "tema-20",
    "name": "Areia 5",
    "palette": "Areia",
    "primary": "#9a6b38",
    "background": "#fbf8f1",
    "text": "#33281d",
    "surface": "#f1e6d2",
    "font": "Montserrat",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Ateliê"
  },
  {
    "id": "tema-21",
    "name": "Ameixa 1",
    "palette": "Ameixa",
    "primary": "#71456f",
    "background": "#faf6fb",
    "text": "#2d1e2b",
    "surface": "#ebdced",
    "font": "Inter",
    "spacing": "airy",
    "radius": 22,
    "layout": "Horizonte"
  },
  {
    "id": "tema-22",
    "name": "Ameixa 2",
    "palette": "Ameixa",
    "primary": "#71456f",
    "background": "#faf6fb",
    "text": "#2d1e2b",
    "surface": "#ebdced",
    "font": "Sora",
    "spacing": "compact",
    "radius": 8,
    "layout": "Editorial"
  },
  {
    "id": "tema-23",
    "name": "Ameixa 3",
    "palette": "Ameixa",
    "primary": "#71456f",
    "background": "#faf6fb",
    "text": "#2d1e2b",
    "surface": "#ebdced",
    "font": "Poppins",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Galeria"
  },
  {
    "id": "tema-24",
    "name": "Ameixa 4",
    "palette": "Ameixa",
    "primary": "#71456f",
    "background": "#faf6fb",
    "text": "#2d1e2b",
    "surface": "#ebdced",
    "font": "DM Sans",
    "spacing": "airy",
    "radius": 22,
    "layout": "Essencial"
  },
  {
    "id": "tema-25",
    "name": "Ameixa 5",
    "palette": "Ameixa",
    "primary": "#71456f",
    "background": "#faf6fb",
    "text": "#2d1e2b",
    "surface": "#ebdced",
    "font": "Montserrat",
    "spacing": "compact",
    "radius": 8,
    "layout": "Ateliê"
  },
  {
    "id": "tema-26",
    "name": "Grafite 1",
    "palette": "Grafite",
    "primary": "#3c4856",
    "background": "#f5f6f8",
    "text": "#18202a",
    "surface": "#e0e4ea",
    "font": "Inter",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Horizonte"
  },
  {
    "id": "tema-27",
    "name": "Grafite 2",
    "palette": "Grafite",
    "primary": "#3c4856",
    "background": "#f5f6f8",
    "text": "#18202a",
    "surface": "#e0e4ea",
    "font": "Sora",
    "spacing": "airy",
    "radius": 22,
    "layout": "Editorial"
  },
  {
    "id": "tema-28",
    "name": "Grafite 3",
    "palette": "Grafite",
    "primary": "#3c4856",
    "background": "#f5f6f8",
    "text": "#18202a",
    "surface": "#e0e4ea",
    "font": "Poppins",
    "spacing": "compact",
    "radius": 8,
    "layout": "Galeria"
  },
  {
    "id": "tema-29",
    "name": "Grafite 4",
    "palette": "Grafite",
    "primary": "#3c4856",
    "background": "#f5f6f8",
    "text": "#18202a",
    "surface": "#e0e4ea",
    "font": "DM Sans",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Essencial"
  },
  {
    "id": "tema-30",
    "name": "Grafite 5",
    "palette": "Grafite",
    "primary": "#3c4856",
    "background": "#f5f6f8",
    "text": "#18202a",
    "surface": "#e0e4ea",
    "font": "Montserrat",
    "spacing": "airy",
    "radius": 22,
    "layout": "Ateliê"
  },
  {
    "id": "tema-31",
    "name": "Sálvia 1",
    "palette": "Sálvia",
    "primary": "#66856f",
    "background": "#f4f8f3",
    "text": "#24342a",
    "surface": "#deeadf",
    "font": "Inter",
    "spacing": "compact",
    "radius": 8,
    "layout": "Horizonte"
  },
  {
    "id": "tema-32",
    "name": "Sálvia 2",
    "palette": "Sálvia",
    "primary": "#66856f",
    "background": "#f4f8f3",
    "text": "#24342a",
    "surface": "#deeadf",
    "font": "Sora",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Editorial"
  },
  {
    "id": "tema-33",
    "name": "Sálvia 3",
    "palette": "Sálvia",
    "primary": "#66856f",
    "background": "#f4f8f3",
    "text": "#24342a",
    "surface": "#deeadf",
    "font": "Poppins",
    "spacing": "airy",
    "radius": 22,
    "layout": "Galeria"
  },
  {
    "id": "tema-34",
    "name": "Sálvia 4",
    "palette": "Sálvia",
    "primary": "#66856f",
    "background": "#f4f8f3",
    "text": "#24342a",
    "surface": "#deeadf",
    "font": "DM Sans",
    "spacing": "compact",
    "radius": 8,
    "layout": "Essencial"
  },
  {
    "id": "tema-35",
    "name": "Sálvia 5",
    "palette": "Sálvia",
    "primary": "#66856f",
    "background": "#f4f8f3",
    "text": "#24342a",
    "surface": "#deeadf",
    "font": "Montserrat",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Ateliê"
  },
  {
    "id": "tema-36",
    "name": "Dourado 1",
    "palette": "Dourado",
    "primary": "#a97728",
    "background": "#fffaf0",
    "text": "#332817",
    "surface": "#f5e7bf",
    "font": "Inter",
    "spacing": "airy",
    "radius": 22,
    "layout": "Horizonte"
  },
  {
    "id": "tema-37",
    "name": "Dourado 2",
    "palette": "Dourado",
    "primary": "#a97728",
    "background": "#fffaf0",
    "text": "#332817",
    "surface": "#f5e7bf",
    "font": "Sora",
    "spacing": "compact",
    "radius": 8,
    "layout": "Editorial"
  },
  {
    "id": "tema-38",
    "name": "Dourado 3",
    "palette": "Dourado",
    "primary": "#a97728",
    "background": "#fffaf0",
    "text": "#332817",
    "surface": "#f5e7bf",
    "font": "Poppins",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Galeria"
  },
  {
    "id": "tema-39",
    "name": "Dourado 4",
    "palette": "Dourado",
    "primary": "#a97728",
    "background": "#fffaf0",
    "text": "#332817",
    "surface": "#f5e7bf",
    "font": "DM Sans",
    "spacing": "airy",
    "radius": 22,
    "layout": "Essencial"
  },
  {
    "id": "tema-40",
    "name": "Dourado 5",
    "palette": "Dourado",
    "primary": "#a97728",
    "background": "#fffaf0",
    "text": "#332817",
    "surface": "#f5e7bf",
    "font": "Montserrat",
    "spacing": "compact",
    "radius": 8,
    "layout": "Ateliê"
  },
  {
    "id": "tema-41",
    "name": "Azul noite 1",
    "palette": "Azul noite",
    "primary": "#324b78",
    "background": "#f4f6fb",
    "text": "#18223c",
    "surface": "#dce4f5",
    "font": "Inter",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Horizonte"
  },
  {
    "id": "tema-42",
    "name": "Azul noite 2",
    "palette": "Azul noite",
    "primary": "#324b78",
    "background": "#f4f6fb",
    "text": "#18223c",
    "surface": "#dce4f5",
    "font": "Sora",
    "spacing": "airy",
    "radius": 22,
    "layout": "Editorial"
  },
  {
    "id": "tema-43",
    "name": "Azul noite 3",
    "palette": "Azul noite",
    "primary": "#324b78",
    "background": "#f4f6fb",
    "text": "#18223c",
    "surface": "#dce4f5",
    "font": "Poppins",
    "spacing": "compact",
    "radius": 8,
    "layout": "Galeria"
  },
  {
    "id": "tema-44",
    "name": "Azul noite 4",
    "palette": "Azul noite",
    "primary": "#324b78",
    "background": "#f4f6fb",
    "text": "#18223c",
    "surface": "#dce4f5",
    "font": "DM Sans",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Essencial"
  },
  {
    "id": "tema-45",
    "name": "Azul noite 5",
    "palette": "Azul noite",
    "primary": "#324b78",
    "background": "#f4f6fb",
    "text": "#18223c",
    "surface": "#dce4f5",
    "font": "Montserrat",
    "spacing": "airy",
    "radius": 22,
    "layout": "Ateliê"
  },
  {
    "id": "tema-46",
    "name": "Rosa pétala 1",
    "palette": "Rosa pétala",
    "primary": "#b85d79",
    "background": "#fff7fa",
    "text": "#3a2029",
    "surface": "#f6dce5",
    "font": "Inter",
    "spacing": "compact",
    "radius": 8,
    "layout": "Horizonte"
  },
  {
    "id": "tema-47",
    "name": "Rosa pétala 2",
    "palette": "Rosa pétala",
    "primary": "#b85d79",
    "background": "#fff7fa",
    "text": "#3a2029",
    "surface": "#f6dce5",
    "font": "Sora",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Editorial"
  },
  {
    "id": "tema-48",
    "name": "Rosa pétala 3",
    "palette": "Rosa pétala",
    "primary": "#b85d79",
    "background": "#fff7fa",
    "text": "#3a2029",
    "surface": "#f6dce5",
    "font": "Poppins",
    "spacing": "airy",
    "radius": 22,
    "layout": "Galeria"
  },
  {
    "id": "tema-49",
    "name": "Rosa pétala 4",
    "palette": "Rosa pétala",
    "primary": "#b85d79",
    "background": "#fff7fa",
    "text": "#3a2029",
    "surface": "#f6dce5",
    "font": "DM Sans",
    "spacing": "compact",
    "radius": 8,
    "layout": "Essencial"
  },
  {
    "id": "tema-50",
    "name": "Rosa pétala 5",
    "palette": "Rosa pétala",
    "primary": "#b85d79",
    "background": "#fff7fa",
    "text": "#3a2029",
    "surface": "#f6dce5",
    "font": "Montserrat",
    "spacing": "balanced",
    "radius": 14,
    "layout": "Ateliê"
  }
];
